dist: focal
language: node_js
node_js: 
  - 16
  - 18
  - 19

git:
  autocrlf: false


addons:
  apt:
    packages: expect
  homebrew:
    packages: expect

os:
  - linux
  - osx
  - windows

osx_image:
  - xcode14

cache:
  npm: false

jobs:
  exclude:
    - osx_image: xcode14
      node_js: 16


script:
  - npm t
  - npm run test-templates
  - npm run test-all-commands
  - npm run test-lib-import
  # - sh tests/test-npx.sh