dist: focal
language: node_js
node_js: 
  - 16
  - 18
  - 19

git:
  autocrlf: false

before_install:

os:
  - linux
  - osx
  - windows

osx_image:
  - xcode14


jobs:
  exclude:
    - osx_image: xcode14
      node_js: 16
    # Only test on linux for regular test jobs
    - if: branch != master
      node_js: 18
    - if: branch != master
      node_js: 19
    - if: type = pull_request
      os: osx
    - if: type = pull_request
      os: windows

script:
  - npm t
  - npm run test-templates
  - npm run test-all-commands
  - npm run test-lib-import
  - if [ $TRAVIS_EVENT_TYPE == "cron" ] ; then sh test-npx.sh ; fi