dist: focal
language: node_js

git:
  autocrlf: false


addons:
  apt:
    packages: expect
  homebrew:
    packages: expect


jobs:
  include:
    - os: osx
      node_js: 16
    - os: linux
      node_js: 18
    - os: windows
      node_js: 20

cache:
  npm: false



script:
  - npm t
  # - npm run test-templates
  # - npm run test-lib-import
  - |
    echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
    echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run test-all-commands; fi
  # - sh tests/test-npx.sh