dist: focal
language: node_js
node_js: 
  - 16
  - 18

git:
  autocrlf: false


addons:
  apt:
    packages: expect
  homebrew:
    packages: expect

os:
  - linux
  - osx
  - windows

osx_image:
  - xcode12

cache:
  npm: false




script:
  - npm t
  # - npm run test-templates
  # - npm run test-lib-import
  - |
    if [ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]; then
      npm run test-all-commands; 
    fi
  # - sh tests/test-npx.sh