dist: focal
language: node_js

git:
  autocrlf: false


addons:
  apt:
    packages: expect
  homebrew:
    packages: expect


jobs:
  include:
    - os: osx
      node_js: 16
    - os: linux
      node_js: 18
    - os: windows
      node_js: 20

cache:
  npm: false



script:
  - npm t
  # - npm run test-templates
  # - npm run test-lib-import
  - |
    if [ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]; then
      npm run test-all-commands; 
    fi
  # - sh tests/test-npx.sh