dist: focal
language: node_js

git:
  autocrlf: false


addons:
  apt:
    packages: expect
  homebrew:
    packages: expect


os: 

  - linux


osx_image: xcode14

nodejs:
  - 16
  - 18
  - 20

cache:
  npm: false



script:
  # - npm t
  # - npm run test-templates
  # - npm run test-lib-import
  - |
    echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
    echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "# master"; 
      npm run test-all-commands; 
    else
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        echo "# no master, just run on linux"; 
        npm run test-all-commands; 
      fi
    fi
  # - sh tests/test-npx.sh